#ifndef CONFIGS_H
#define CONFIGS_H

#define BAUDRATE    115200

#define FIRST_LED        13
#define SECOND_LED       12
#define ON_OFF_BUTTON_PIN 10

#define DEBOUNCE_TIME_MS   50

#define JOYSTICK_X_PIN A0
#define JOYSTICK_Y_PIN A1
#define JOYSTICK_BUTTON_PIN A2

#define JOYSTICK_RECURENCE_MS  50
#define REPORT_RECURRENCE_MS   500

#define NUM_ELEMENTS_MEDIAN_FILTER   7

#endif
